import type { Metadata } from "next";
import Link from "next/link";
import { GrantCard } from "../../components/grant-card";
import { Pagination } from "../../components/pagination";
import { SearchForm } from "../../components/search-form";
import { SiteHeader } from "../../components/site-header";
import { searchGrants } from "../../lib/db/grants";
import { parseSearchParams } from "../../lib/db/query-params";
export const dynamic = "force-dynamic";
export async function generateMetadata({ searchParams }: { searchParams: Params }): Promise<Metadata> { const params = await searchParams; const hasQuery = Object.values(params).some((value) => Array.isArray(value) ? value.some(Boolean) : Boolean(value)); return { title: "Convocatorias", description: "Explora convocatorias públicas procedentes de la BDNS/SNPSAP.", alternates: { canonical: "/subvenciones" }, robots: hasQuery ? { index: false, follow: true } : undefined }; }
type Params = Promise<Record<string, string | string[] | undefined>>;
function one(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
export default async function GrantsPage({ searchParams }: { searchParams: Params }) { const params = await searchParams; const filters = parseSearchParams(params); let result; try { result = await searchGrants(filters); } catch { return <><SiteHeader/><main className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><h1 className="text-3xl font-semibold">Convocatorias</h1><p className="mt-4 rounded-lg bg-amber-50 p-4 text-amber-900">No se ha podido consultar el catálogo local. Comprueba que la base de datos esté disponible.</p></main></>; } const query = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { const v = one(value); if (v) query.set(key, v); }); return <><SiteHeader/><main className="mx-auto w-full max-w-6xl px-4 py-10 sm:px-6"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-amber-700">Discovery</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Convocatorias públicas</h1><p className="mt-3 text-slate-600">{result.total} resultados en el dataset local.</p><div className="mt-7"><SearchForm initialValue={filters.q}/></div></div><div className="mt-8 flex flex-wrap gap-2 text-sm"><Link href="/subvenciones?status=open" className="rounded-full border border-slate-300 px-3 py-2 hover:bg-slate-50">Solo abiertas</Link><Link href="/subvenciones" className="rounded-full border border-slate-300 px-3 py-2 hover:bg-slate-50">Limpiar filtros</Link></div><section className="mt-8 grid gap-4">{result.items.length ? result.items.map((grant) => <GrantCard grant={grant} key={grant.bdnsCode}/>) : <p className="rounded-xl border border-dashed border-slate-300 p-8 text-slate-600">No hay convocatorias con estos filtros.</p>}</section><div className="mt-8"><Pagination page={result.page} total={result.total} pageSize={result.pageSize} query={query}/></div></main></>; }
