import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import { Breadcrumbs, ProvenancePanel, SiteFooter } from "../../../components/discovery";
import { BudgetDisplay, DateDisplay, GrantStatus } from "../../../components/grant-card";
import { SiteHeader } from "../../../components/site-header";
import { getGrantByCode } from "../../../lib/db/grants";
import { grantSlug } from "../../../lib/slug";

type Props = { params: Promise<{ slug: string }> };
export const dynamic = "force-dynamic";
function codeFrom(slug: string) { return slug.match(/^([^ -]+)-/)?.[1] ?? slug.split("-")[0]; }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const code = codeFrom(slug); const grant = await getGrantByCode(code); return grant ? { title: grant.title ?? "Convocatoria pública", description: grant.description ?? "Convocatoria pública de la BDNS/SNPSAP.", alternates: { canonical: `/subvenciones/${grant.slug}` } } : {}; }

export default async function GrantPage({ params }: Props) {
  const { slug } = await params; const code = codeFrom(slug); const grant = await getGrantByCode(code); if (!grant) notFound(); const canonical = grantSlug(grant.bdnsCode, grant.title ?? "Convocatoria sin título"); if (slug !== canonical) redirect(`/subvenciones/${canonical}`);
  return <><SiteHeader/><main id="main-content" className="container-shell py-10 sm:py-14"><Breadcrumbs items={[{ label: "Subvenciones", href: "/subvenciones" }, { label: `BDNS ${grant.bdnsCode}` }]}/><header className="mt-10 max-w-4xl"><GrantStatus isOpen={grant.isOpen} endDate={grant.applicationEndDate}/><p className="mt-3 text-xs font-semibold uppercase tracking-[.12em] text-[var(--subtle)]">BDNS {grant.bdnsCode}</p><h1 className="mt-3 text-4xl font-semibold leading-[1.03] tracking-[-.05em] sm:text-6xl">{grant.title ?? "Convocatoria sin título"}</h1><p className="mt-5 text-base text-[var(--muted)]">{grant.organizations.map((item) => item.label).join(" · ") || "Información no disponible en la fuente"}</p></header>
    <section aria-label="Resumen de la convocatoria" className="mt-10 grid border-y border-[var(--border)] sm:grid-cols-2 lg:grid-cols-4"><div className="border-b border-[var(--border)] py-5 sm:border-r sm:pr-6 lg:border-b-0"><p className="text-xs font-semibold uppercase tracking-[.1em] text-[var(--subtle)]">Presupuesto publicado</p><p className="mt-2 text-lg font-semibold"><BudgetDisplay value={grant.totalBudget}/></p></div><div className="border-b border-[var(--border)] py-5 sm:pl-6 lg:border-b-0 lg:border-r lg:pr-6"><p className="text-xs font-semibold uppercase tracking-[.1em] text-[var(--subtle)]">Territorio</p><p className="mt-2 text-sm leading-6">{grant.regions.map((item) => item.label).join(" · ") || "Información no disponible en la fuente"}</p></div><div className="border-b border-[var(--border)] py-5 sm:pr-6 lg:border-b-0 lg:border-r lg:pl-6"><p className="text-xs font-semibold uppercase tracking-[.1em] text-[var(--subtle)]">Quién puede beneficiarse</p><p className="mt-2 text-sm leading-6">{grant.beneficiaryTypes.map((item) => item.label).join(" · ") || "Información no disponible en la fuente"}</p></div><div className="py-5 sm:pl-6"><p className="text-xs font-semibold uppercase tracking-[.1em] text-[var(--subtle)]">Plazo de solicitud</p><p className="mt-2 text-sm leading-6"><DateDisplay start={grant.applicationStartDate} end={grant.applicationEndDate} isOpen={grant.isOpen}/></p></div></section>
    <div className="mt-12 grid gap-12 lg:grid-cols-[minmax(0,44rem)_minmax(15rem,1fr)] lg:gap-20"><article className="min-w-0"><section><p className="eyebrow">Sobre esta convocatoria</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em]">Finalidad y descripción</h2>{grant.purposeDescription && <p className="body-copy mt-5 text-base">{grant.purposeDescription}</p>}<p className="mt-5 whitespace-pre-line text-base leading-8 text-[var(--muted)]">{grant.description ?? "Información no disponible en la fuente"}</p></section>{grant.regulatoryBasesDescription && <section className="mt-12 border-t border-[var(--border)] pt-8"><p className="eyebrow">Marco regulador</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em]">Bases reguladoras</h2><p className="mt-5 whitespace-pre-line text-base leading-8 text-[var(--muted)]">{grant.regulatoryBasesDescription}</p>{grant.regulatoryBasesUrl && <a className="focus-ring mt-5 inline-flex rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[var(--accent-hover)]" href={grant.regulatoryBasesUrl} target="_blank" rel="noreferrer">Consultar bases reguladoras ↗</a>}</section>}{grant.sectors.length > 0 && <section className="mt-12 border-t border-[var(--border)] pt-8"><p className="eyebrow">Clasificación</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em]">Sectores y fondos</h2><dl className="mt-5 grid gap-5 text-sm sm:grid-cols-2"><div><dt className="text-[var(--subtle)]">Sectores</dt><dd className="mt-1 leading-6">{grant.sectors.map((item) => item.label).join(" · ")}</dd></div>{grant.funds.length > 0 && <div><dt className="text-[var(--subtle)]">Fondos</dt><dd className="mt-1 leading-6">{grant.funds.map((item) => item.label).join(" · ")}</dd></div>}</dl></section>}</article><aside className="space-y-8"><section className="panel p-5"><p className="eyebrow">Fuente oficial</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Para consultar requisitos completos, documentación y realizar cualquier trámite, revisa siempre la publicación oficial.</p>{grant.electronicOfficeUrl ? <a className="focus-ring mt-5 inline-flex w-full justify-center rounded-lg bg-[var(--accent)] px-4 py-3 text-sm font-semibold text-white hover:bg-[var(--accent-hover)]" href={grant.electronicOfficeUrl} target="_blank" rel="noreferrer">Ver convocatoria en la fuente oficial ↗</a> : <p className="mt-5 text-xs text-[var(--subtle)]">URL oficial no disponible en la fuente.</p>}</section><ProvenancePanel grant={grant}/></aside></div></main><SiteFooter/></>;
}
