import Link from "next/link";
import { GrantCard } from "./grant-card";
import type { BeneficiarySummary, GrantSummary, RegionSummary, SearchFilters, SectorSummary, TaxonomySummary } from "../lib/db/types";
import { absoluteSiteUrl } from "../lib/site";
import { safeJsonLd } from "../lib/seo";

export function Breadcrumbs({ items }: { items: Array<{ label: string; href?: string }> }) { const entries = [{ label: "Inicio", href: "/" }, ...items]; const jsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: entries.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.label, ...(item.href ? { item: absoluteSiteUrl(item.href) } : {}) })) }; return <><nav aria-label="Migas de pan" className="text-xs text-[var(--muted)]"><Link href="/" className="hover:text-[var(--foreground)]">Inicio</Link>{items.map((item) => <span key={`${item.label}-${item.href ?? "current"}`}><span aria-hidden="true" className="mx-2 text-[var(--subtle)]">/</span>{item.href ? <Link href={item.href} className="hover:text-[var(--foreground)]">{item.label}</Link> : <span aria-current="page">{item.label}</span>}</span>)}</nav><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(jsonLd) }}/></>; }

export function EmptyState({ query = false }: { query?: boolean }) { return <div className="panel px-6 py-10 text-center"><p className="text-lg font-semibold text-[var(--foreground)]">No hemos encontrado convocatorias con estos filtros.</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--muted)]">Prueba a quitar algún filtro o buscar otros términos en los datos disponibles.</p>{query && <Link href="/subvenciones" className="focus-ring mt-5 inline-flex rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[var(--accent-hover)]">Limpiar filtros</Link>}</div>; }
export function ErrorState({ message = "No hemos podido cargar la información. Inténtalo de nuevo en unos instantes." }: { message?: string }) { return <div role="alert" className="border border-[#e5c9a3] bg-[#fff8ed] px-5 py-4 text-sm text-[#7a531f]"><p className="font-semibold">No hemos podido completar la consulta</p><p className="mt-1">{message}</p></div>; }

export function ActiveFilters({ filters }: { filters: SearchFilters }) {
  const active = [{ key: "q", label: filters.q ? `“${filters.q}”` : null }, { key: "region", label: filters.region }, { key: "sector", label: filters.sector }, { key: "beneficiary", label: filters.beneficiary }, { key: "status", label: filters.status === "open" ? "Abiertas" : null }, { key: "minBudget", label: filters.minBudget !== undefined ? `Desde ${filters.minBudget.toLocaleString("es-ES")} €` : null }].filter((item): item is { key: string; label: string } => Boolean(item.label));
  if (!active.length) return null;
  const removeFilter = (key: string) => { const query = new URLSearchParams(); if (filters.q && key !== "q") query.set("q", filters.q); if (filters.region && key !== "region") query.set("region", filters.region); if (filters.sector && key !== "sector") query.set("sector", filters.sector); if (filters.beneficiary && key !== "beneficiary") query.set("beneficiary", filters.beneficiary); if (filters.status && key !== "status") query.set("status", filters.status); if (filters.minBudget !== undefined && key !== "minBudget") query.set("minBudget", String(filters.minBudget)); if (filters.sort && filters.sort !== "recent") query.set("sort", filters.sort); const value = query.toString(); return value ? `/subvenciones?${value}` : "/subvenciones"; };
  return <div className="flex flex-wrap items-center gap-2" aria-label="Filtros activos"><span className="mr-1 text-xs font-semibold uppercase tracking-[.12em] text-[var(--subtle)]">Filtrado por</span>{active.map((item) => <Link key={item.key} href={removeFilter(item.key)} aria-label={`Quitar filtro ${item.label}`} className="focus-ring inline-flex items-center rounded-full bg-[var(--accent-soft)] px-3 py-1.5 text-xs font-medium text-[var(--accent-hover)] hover:bg-[var(--accent-soft-strong)]">{item.label}<span aria-hidden="true" className="ml-1.5 text-sm">×</span></Link>)}<Link href="/subvenciones" className="focus-ring ml-1 text-xs font-semibold text-[var(--accent)] underline underline-offset-4">Limpiar filtros</Link></div>;
}

function fieldQuery(params: Record<string, string | undefined>) { const query = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value) query.set(key, value); }); return `/subvenciones?${query.toString()}`; }

export function FilterPanel({ filters, regions, sectors, beneficiaries }: { filters: SearchFilters; regions: RegionSummary[]; sectors: SectorSummary[]; beneficiaries: BeneficiarySummary[] }) {
  return <form action="/subvenciones" method="get" className="panel grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-[1.2fr_1fr_1fr_1fr_1fr_1fr_auto] lg:items-end">
    <div className="sm:col-span-2 lg:col-span-1"><label htmlFor="filter-q" className="mb-1.5 block text-xs font-semibold text-[var(--muted)]">Buscar</label><input id="filter-q" name="q" defaultValue={filters.q} placeholder="Título, finalidad..." className="focus-ring min-h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 text-sm"/></div>
    <label className="text-xs font-semibold text-[var(--muted)]">Región<select name="region" defaultValue={filters.region ?? ""} className="focus-ring mt-1.5 min-h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 text-sm font-normal"><option value="">Todas</option>{regions.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label>
    <label className="text-xs font-semibold text-[var(--muted)]">Sector<select name="sector" defaultValue={filters.sector ?? ""} className="focus-ring mt-1.5 min-h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 text-sm font-normal"><option value="">Todos</option>{sectors.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label>
    <label className="text-xs font-semibold text-[var(--muted)]">Beneficiario<select name="beneficiary" defaultValue={filters.beneficiary ?? ""} className="focus-ring mt-1.5 min-h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 text-sm font-normal"><option value="">Todos</option>{beneficiaries.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label>
    <label className="text-xs font-semibold text-[var(--muted)]">Presupuesto mínimo<input name="minBudget" inputMode="decimal" defaultValue={filters.minBudget} placeholder="0 €" className="focus-ring mt-1.5 min-h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 text-sm font-normal"/></label>
    <label className="text-xs font-semibold text-[var(--muted)]">Ordenar<select name="sort" defaultValue={filters.sort ?? "recent"} className="focus-ring mt-1.5 min-h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 text-sm font-normal"><option value="recent">Más recientes</option><option value="budget-desc">Mayor presupuesto</option><option value="budget-asc">Menor presupuesto</option></select></label>
    <div className="flex flex-wrap items-center gap-3 sm:col-span-2 lg:col-span-1"><div><label className="flex items-center gap-2 text-xs font-semibold text-[var(--muted)]"><input type="checkbox" name="status" value="open" defaultChecked={filters.status === "open"} className="focus-ring h-4 w-4 accent-[var(--accent)]"/> Sólo abiertas</label><p className="mt-1 text-[11px] font-normal leading-4 text-[var(--subtle)]">Estado según BDNS</p></div><button className="focus-ring min-h-10 flex-1 rounded-lg bg-[var(--accent)] px-4 text-sm font-semibold text-white hover:bg-[var(--accent-hover)]" type="submit">Aplicar</button><Link href={fieldQuery({})} className="focus-ring inline-flex min-h-10 items-center rounded-lg border border-[var(--border-strong)] px-3 text-sm text-[var(--foreground)] hover:bg-[var(--background)]">Limpiar</Link></div>
  </form>;
}

export function SortSelect({ filters }: { filters: SearchFilters }) { return <label className="flex items-center gap-2 text-sm text-[var(--muted)]">Ordenar<select name="sort" form="sort-form" defaultValue={filters.sort ?? "recent"} className="focus-ring rounded-lg border border-[var(--border)] bg-white px-3 py-2 text-sm font-medium text-[var(--foreground)]"><option value="recent">Más recientes</option><option value="budget-desc">Mayor presupuesto</option><option value="budget-asc">Menor presupuesto</option></select></label>; }

export function GrantList({ items, total, emptyQuery }: { items: GrantSummary[]; total: number; emptyQuery: boolean }) { return <section aria-label="Resultados de convocatorias"><div className="mb-2 flex items-center justify-between gap-4"><h2 className="section-title">Resultados</h2><span className="text-right text-sm text-[var(--muted)]">{total.toLocaleString("es-ES")} convocatorias encontradas en los datos disponibles</span></div>{items.length ? <div>{items.map((grant) => <GrantCard grant={grant} key={grant.bdnsCode}/>)}</div> : <EmptyState query={emptyQuery}/>}</section>; }

export function OpenOpportunitySection({ grants }: { grants: GrantSummary[] }) { return <section className="container-shell py-16 sm:py-20"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-[var(--border)] pb-5"><div><p className="eyebrow">Ahora disponible</p><h2 className="section-title mt-2">Oportunidades abiertas</h2><p className="body-copy mt-2 max-w-xl text-sm">Convocatorias marcadas como abiertas por la BDNS. No inferimos una fecha de cierre cuando la fuente no la indica.</p></div><Link href="/subvenciones?status=open" className="focus-ring text-sm font-semibold text-[var(--accent)] underline underline-offset-4">Ver todas →</Link></div><div className="mt-2">{grants.length ? grants.slice(0, 4).map((grant) => <GrantCard grant={grant} key={grant.bdnsCode}/>) : <p className="py-8 text-sm text-[var(--muted)]">No hay convocatorias marcadas como abiertas en los datos disponibles.</p>}</div></section>; }

function TaxonomyLink({ item, basePath }: { item: TaxonomySummary; basePath: string }) { return <Link href={`${basePath}/${item.slug}`} className="focus-ring group flex items-center justify-between border-b border-[var(--border)] py-4 transition-colors hover:border-[var(--accent)]"><span><span className="block font-semibold tracking-[-.015em] text-[var(--foreground)] group-hover:text-[var(--accent)]">{item.label}</span><span className="mt-1 block text-xs text-[var(--muted)]">{item.totalGrants.toLocaleString("es-ES")} convocatorias · {item.openGrants} abiertas</span></span><span className="text-lg text-[var(--accent)] transition-transform group-hover:translate-x-1" aria-hidden="true">→</span></Link>; }
export function ExplorationSection({ sectors, regions, beneficiaries }: { sectors: SectorSummary[]; regions: RegionSummary[]; beneficiaries: BeneficiarySummary[] }) { return <section className="container-shell grid gap-12 border-t border-[var(--border)] py-16 sm:grid-cols-3 sm:gap-8 sm:py-20"><div><p className="eyebrow">Explora</p><h2 className="mt-2 text-xl font-semibold tracking-[-.025em]">Por sector</h2><div className="mt-4">{sectors.slice(0, 6).map((item) => <TaxonomyLink key={item.key} item={item} basePath="/subvenciones/sector"/>)}</div><Link href="/subvenciones/sector" className="focus-ring mt-5 inline-block text-sm font-semibold text-[var(--accent)] underline underline-offset-4">Todos los sectores →</Link></div><div><p className="eyebrow">Territorio</p><h2 className="mt-2 text-xl font-semibold tracking-[-.025em]">Por región</h2><div className="mt-4">{regions.slice(0, 6).map((item) => <TaxonomyLink key={item.key} item={item} basePath="/subvenciones/region"/>)}</div><Link href="/subvenciones/region" className="focus-ring mt-5 inline-block text-sm font-semibold text-[var(--accent)] underline underline-offset-4">Todas las regiones →</Link></div><div><p className="eyebrow">Personas y entidades</p><h2 className="mt-2 text-xl font-semibold tracking-[-.025em]">Por beneficiario</h2><div className="mt-4">{beneficiaries.slice(0, 6).map((item) => <TaxonomyLink key={item.key} item={item} basePath="/subvenciones/beneficiario"/>)}</div><Link href="/subvenciones/beneficiario" className="focus-ring mt-5 inline-block text-sm font-semibold text-[var(--accent)] underline underline-offset-4">Todos los beneficiarios →</Link></div></section>; }

export function DatasetStats({ total, open, sectors, regions }: { total: number; open: number; sectors: number; regions: number }) { return <section className="border-y border-[var(--border)] bg-white"><div className="container-shell py-12 sm:py-16"><div className="max-w-2xl"><p className="eyebrow">Intelligence en contexto</p><h2 className="section-title mt-2">Lo que puedes consultar hoy</h2><p className="body-copy mt-3 text-sm">Estas cifras reflejan las convocatorias que hemos incorporado hasta ahora desde BDNS. La cobertura es parcial y seguirá ampliándose.</p></div><dl className="mt-10 grid grid-cols-2 gap-y-8 sm:grid-cols-4 sm:gap-6"><div><dt className="text-sm text-[var(--muted)]">Convocatorias incorporadas</dt><dd className="mt-2 text-3xl font-semibold tracking-[-.05em]">{total.toLocaleString("es-ES")}</dd></div><div><dt className="text-sm text-[var(--muted)]">Marcadas como abiertas</dt><dd className="mt-2 text-3xl font-semibold tracking-[-.05em] text-[var(--accent)]">{open.toLocaleString("es-ES")}</dd></div><div><dt className="text-sm text-[var(--muted)]">Sectores representados</dt><dd className="mt-2 text-3xl font-semibold tracking-[-.05em]">{sectors.toLocaleString("es-ES")}</dd></div><div><dt className="text-sm text-[var(--muted)]">Territorios representados</dt><dd className="mt-2 text-3xl font-semibold tracking-[-.05em]">{regions.toLocaleString("es-ES")}</dd></div></dl></div></section>; }

export function SourceTrustSection() { return <section className="container-shell py-16 sm:py-20"><div className="max-w-2xl border-l-2 border-[var(--accent)] pl-5 sm:pl-7"><p className="eyebrow">Fuente y confianza</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em]">Información pública, organizada con contexto.</h2><p className="body-copy mt-3 text-sm">Oportexa organiza información procedente de la Base de Datos Nacional de Subvenciones (BDNS/SNPSAP). La fuente oficial continúa siendo BDNS; para la información definitiva, consulta siempre la convocatoria original.</p><p className="mt-4 text-xs leading-5 text-[var(--subtle)]">Puede existir un retraso entre la fuente y la observación local. Oportexa no es la administración pública ni sustituye asesoramiento jurídico, fiscal o administrativo.</p></div></section>; }

export function ProvenancePanel({ grant }: { grant: { bdnsCode: string; sourceReceivedDate: string | null; firstSeenAt: string; lastSeenAt: string } }) { return <section className="border-t border-[var(--border)] pt-7"><p className="eyebrow">Procedencia</p><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-[var(--subtle)]">Fuente oficial</dt><dd className="mt-1 font-semibold">Base de Datos Nacional de Subvenciones (BDNS / SNPSAP)</dd></div><div><dt className="text-[var(--subtle)]">Código BDNS</dt><dd className="mt-1 font-semibold">{grant.bdnsCode}</dd></div>{grant.sourceReceivedDate && <div><dt className="text-[var(--subtle)]">Fecha recibida de fuente</dt><dd className="mt-1">{grant.sourceReceivedDate}</dd></div>}<div><dt className="text-[var(--subtle)]">Primera vez observada por Oportexa</dt><dd className="mt-1">{grant.firstSeenAt}</dd></div><div><dt className="text-[var(--subtle)]">Última vez observada por Oportexa</dt><dd className="mt-1">{grant.lastSeenAt}</dd></div></dl><p className="mt-4 text-xs leading-5 text-[var(--subtle)]">Las fechas de observación corresponden a Oportexa y no representan necesariamente una fecha oficial de actualización de BDNS.</p></section>; }

export function SiteFooter() { return <footer className="border-t border-[var(--border)] bg-[var(--foreground)] text-white"><div className="container-shell grid gap-10 py-12 sm:grid-cols-[1.4fr_1fr_1fr]"><div><p className="font-bold tracking-[-.03em]">Oportexa<span className="ml-1 text-[#9ad3bc]">/</span></p><p className="mt-3 max-w-xs text-sm leading-6 text-white/75">Una forma sencilla de descubrir y entender oportunidades públicas en España.</p></div><div><p className="text-xs font-bold uppercase tracking-[.14em] text-white/75">Explorar</p><div className="mt-4 grid gap-2 text-sm text-white/85"><Link href="/subvenciones" className="hover:text-white">Convocatorias</Link><Link href="/subvenciones/region" className="hover:text-white">Regiones</Link><Link href="/subvenciones/sector" className="hover:text-white">Sectores</Link><Link href="/subvenciones/organismo" className="hover:text-white">Organismos</Link><Link href="/subvenciones/beneficiario" className="hover:text-white">Beneficiarios</Link></div></div><div><p className="text-xs font-bold uppercase tracking-[.14em] text-white/75">Datos</p><p className="mt-4 text-sm leading-6 text-white/80">Fuente inicial: BDNS/SNPSAP.<br/>Cobertura actualmente parcial.<br/>La fuente oficial es BDNS.</p></div></div><div className="container-shell border-t border-white/10 py-5 text-xs text-white/70">Oportexa no sustituye a la fuente oficial ni constituye asesoramiento.</div></footer>; }
