import Link from "next/link";
import { GrantList, Breadcrumbs, SiteFooter } from "./discovery";
import { Pagination } from "./pagination";
import { SiteHeader } from "./site-header";
import type { SearchResult, TaxonomySummary } from "../lib/db/types";

export function TaxonomyCard({ item, basePath }: { item: TaxonomySummary; basePath: string }) { return <Link href={`${basePath}/${item.slug}`} className="focus-ring group flex items-center justify-between border-b border-[var(--border)] py-5 transition-colors hover:border-[var(--accent)]"><span><span className="block text-base font-semibold tracking-[-.02em] text-[var(--foreground)] group-hover:text-[var(--accent)]">{item.label}</span><span className="mt-1 block text-sm text-[var(--muted)]">{item.totalGrants.toLocaleString("es-ES")} convocatorias · {item.openGrants} abiertas según BDNS</span></span><span className="pl-4 text-xl text-[var(--accent)] transition-transform group-hover:translate-x-1" aria-hidden="true">→</span></Link>; }

export function TaxonomyGrid({ items, basePath }: { items: TaxonomySummary[]; basePath: string }) { return items.length ? <div className="mt-8">{items.map((item) => <TaxonomyCard key={item.key} item={item} basePath={basePath}/>)}</div> : <div className="panel mt-8 px-6 py-10 text-center text-sm text-[var(--muted)]">No hay información incorporada para esta clasificación.</div>; }

export function TaxonomyIndex({ title, description, basePath, items }: { title: string; description: string; basePath: string; items: TaxonomySummary[] }) { return <><SiteHeader/><main id="main-content" className="container-shell py-10 sm:py-14"><Breadcrumbs items={[{ label: "Subvenciones", href: "/subvenciones" }, { label: title }]}/><header className="mt-10 max-w-3xl"><p className="eyebrow">Explora el catálogo</p><h1 className="section-title mt-2">{title}</h1><p className="body-copy mt-3 text-base">{description}</p></header><TaxonomyGrid items={items} basePath={basePath}/></main><SiteFooter/></>; }

export function TaxonomyDetail({ entity, sectionLabel, indexPath, result, query, titlePrefix = "Subvenciones de" }: { entity: TaxonomySummary; sectionLabel: string; indexPath: string; result: SearchResult; query: URLSearchParams; titlePrefix?: string }) { return <><SiteHeader/><main id="main-content" className="container-shell py-10 sm:py-14"><Breadcrumbs items={[{ label: "Subvenciones", href: "/subvenciones" }, { label: sectionLabel, href: indexPath }, { label: entity.label }]}/><header className="mt-10 max-w-3xl"><p className="eyebrow">{sectionLabel}</p><h1 className="section-title mt-2">{titlePrefix} {entity.label}</h1><p className="body-copy mt-3 text-base">Convocatorias asociadas a {entity.label} dentro de los datos actualmente incorporados. {entity.totalGrants.toLocaleString("es-ES")} disponibles; {entity.openGrants} marcadas como abiertas según BDNS.</p></header><div className="mt-10"><GrantList items={result.items} total={result.total} emptyQuery={false}/><Pagination page={result.page} total={result.total} pageSize={result.pageSize} query={query}/></div></main><SiteFooter/></>; }
